import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import Navbar from "@/components/sections/Navbar";
import ClientSessionProvider from "@/lib/ClientSessionProvider";
import withAuth from "@/lib/withAuth";
import { PUBLIC_ROUTES } from "@/lib/constants";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const AuthenticatedLayout = withAuth(() => <>{children}</>, PUBLIC_ROUTES);

  return (
    <ClientSessionProvider>
      <html lang="en" className="dark">
        <body className={`h-screen`}>
          <main className="flex flex-col items-center w-full">
            <Navbar />
            <div className="max-w-7xl w-full p-6 pt-12">
              <AuthenticatedLayout />
            </div>
          </main>
        </body>
      </html>
    </ClientSessionProvider>
  );
}
