import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import VerticalNav from "@/components/sections/VerticalNav";
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/components/ui/resizable";
import React from "react";

const links = [
  {
    name: "Home",
    href: "/",
    className: "text-xl font-bold",
  },
  {
    name: "About",
    href: "/about",
  },
  {
    name: "Documentation",
    open: false,
    sublinks: [
      {
        name: "Check for Phrase",
        open: true,
        sublinks: [
          {
            name: "Check for Phrase",
            href: "/docs",
          },
        ],
      },
      {
        name: "Check for Phrase",
        href: "/docs",
      },
    ],
  },
  {
    name: "Configurations",
    open: true,
    sublinks: [
      {
        name: "View Configurations",
        href: "/config",
      },
      {
        name: "Create New Configuration",
        href: "/",
      },
    ],
  },
];

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`h-screen`}>
        <main className="h-full">
          <ResizablePanelGroup
            direction="horizontal"
            className="h-full w-full border"
          >
            {/* Left */}
            <ResizablePanel defaultSize={20}>
              <VerticalNav links={links} />
            </ResizablePanel>
            <ResizableHandle withHandle />

            {/* Right */}
            <ResizablePanel defaultSize={80}>
              <div className="flex h-full p-12 flex-col">{children}</div>
            </ResizablePanel>
          </ResizablePanelGroup>
        </main>
      </body>
    </html>
  );
}
