service: sitewatch-core

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-2'}
  environment:
    DYNAMODB_TABLE_NAME: ${ssm:/sitewatch/${self:provider.stage}/dynamodb/table_name}
    PROCESSOR_LAMBDA_NAME: ${self:service}-${self:provider.stage}-processor
    EXECUTOR_LAMBDA_NAME: ${self:service}-${self:provider.stage}-executor
    REDIS_HOST: ${ssm:/sitewatch/${self:provider.stage}/redis/host}
    REDIS_PORT: ${ssm:/sitewatch/${self:provider.stage}/redis/port}
    REDIS_PASSWORD: ${ssm:/sitewatch/${self:provider.stage}/redis/password}
    USE_REDIS: ${ssm:/sitewatch/${self:provider.stage}/use_redis}
    OPEN_AI_API_KEY: ${ssm:/sitewatch/${self:provider.stage}/open_ai_api_key}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE_NAME}"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource:
        - "arn:aws:lambda:${self:provider.region}:*:function:${self:provider.environment.EXECUTOR_LAMBDA_NAME}"
    - Effect: Allow
      Action:
        - ssm:GetParameter
      Resource:
        - "arn:aws:ssm:${self:provider.region}:*:parameter/url-checker/*"
        - "arn:aws:ssm:${self:provider.region}:*:parameter/sitewatch/*"
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource:
        - "arn:aws:logs:${self:provider.region}:*:log-group:/aws/lambda/*:*"

functions:
  processor:
    handler: lambda_processor.lambda_handler
    memorySize: 512
    events:
      - schedule:
          rate: cron(0/5 * * * ? *) # Runs every 5 minutes
    timeout: 60 # 1 minute
    environment:
      EXECUTOR_LAMBDA_NAME: ${self:provider.environment.EXECUTOR_LAMBDA_NAME}
      email_sender: ${ssm:/url-checker/email-sender}
      email_password: ${ssm:/url-checker/email-password}

  executor:
    handler: lambda_executor.lambda_handler
    memorySize: 512
    timeout: 300 # 5 minutes
    environment:
      oxylab_proxy: ${ssm:/sitewatch/oxylab_proxy}
      email_sender: ${ssm:/url-checker/email-sender}
      email_password: ${ssm:/url-checker/email-password}
      proxy_enabled: ${ssm:/sitewatch/${self:provider.stage}/proxy_enabled}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    strip: false
    runtime: python3.9

package:
  individually: true
  patterns:
    - "!node_modules/**"
    - "!venv/**"
    - "!lambda_test.py"
    - "constants.py"
    - "utils.py"
    - "url_check_functions/**"
  exclude:
    - package.json
    - package-lock.json
    - .gitignore
    - README.md
