service: sitewatch-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:us-east-2:992382695229:table/webchecks
            - arn:aws:dynamodb:us-east-2:992382695229:table/webchecks/index/userid-sk-index

functions:
  createCheck:
    handler: functions/createCheck.handler
    events:
      - http:
          path: items
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent

  getCheck:
    handler: functions/getCheck.handler
    events:
      - http:
          path: items
          method: get
          request:
            parameters:
              querystrings:
                userid: false
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent

  updateCheck:
    handler: functions/updateCheck.handler
    events:
      - http:
          path: items
          method: put
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent

  deleteCheck:
    handler: functions/deleteCheck.handler
    events:
      - http:
          path: items
          method: delete
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
