service: sitewatch-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:us-east-2:992382695229:table/webchecks
            - arn:aws:dynamodb:us-east-2:992382695229:table/webchecks/index/userid-sk-index

functions:
  createCheck:
    handler: functions/createCheck.handler
    events:
      - http:
          path: items
          method: post
          cors: true

  getCheck:
    handler: functions/getCheck.handler
    events:
      - http:
          path: items
          method: get
          request:
            parameters:
              querystrings:
                userid: false
          cors: true

  updateCheck:
    handler: functions/updateCheck.handler
    events:
      - http:
          path: items
          method: put
          cors: true

  deleteCheck:
    handler: functions/deleteCheck.handler
    events:
      - http:
          path: items
          method: delete
          cors: true

  optionsHandler:
    handler: functions/optionsHandler.handler
    events:
      - http:
          path: items
          method: options
          cors: true

package:
  include:
    - functions/**
