service: sitewatch-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:us-east-2:992382695229:table/${ssm:/sitewatch/${self:provider.stage}/dynamodb/tableName}
            - arn:aws:dynamodb:us-east-2:992382695229:table/${ssm:/sitewatch/${self:provider.stage}/dynamodb/tableName}/index/userid-sk-index
        - Effect: Allow
          Action:
            - ssm:GetParameter
          Resource:
            - arn:aws:ssm:us-east-2:992382695229:parameter/sitewatch/${self:provider.stage}/dynamodb/tableName

functions:
  createUser:
    handler: functions/createUser.handler
    environment:
      STAGE: ${self:provider.stage}
    events:
      - http:
          path: users
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent

  createCheck:
    handler: functions/createCheck.handler
    environment:
      STAGE: ${self:provider.stage}
    events:
      - http:
          path: items
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent

  getCheck:
    handler: functions/getCheck.handler
    environment:
      STAGE: ${self:provider.stage}
    events:
      - http:
          path: items
          method: get
          request:
            parameters:
              querystrings:
                userid: false
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent

  getUser:
    handler: functions/getUser.handler
    environment:
      STAGE: ${self:provider.stage}
    events:
      - http:
          path: users
          method: get
          request:
            parameters:
              querystrings:
                userid: false
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent

  updateCheck:
    handler: functions/updateCheck.handler
    environment:
      STAGE: ${self:provider.stage}
    events:
      - http:
          path: items
          method: put
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent

  deleteCheck:
    handler: functions/deleteCheck.handler
    environment:
      STAGE: ${self:provider.stage}
    events:
      - http:
          path: items
          method: delete
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent

  optionsHandlerItems:
    handler: functions/optionsHandler.handler
    environment:
      STAGE: ${self:provider.stage}
    events:
      - http:
          path: items
          method: options
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent

  optionsHandlerUsers:
    handler: functions/optionsHandler.handler
    environment:
      STAGE: ${self:provider.stage}
    events:
      - http:
          path: users
          method: options
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent

package:
  include:
    - functions/**

custom:
  testEvents:
    createCheck:
      body: '{"alias": {"S": "TEST"}, "type": {"S": "TYPE"}}'
