name: E2E Tests

on:
  push:
    branches:
      - main
      - e2e
  pull_request:
    branches:
      - main
      - e2e

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Start Application
        run: npm run start &

      - name: Wait for Application to Be Ready
        run: npx wait-on http://localhost:3000

      - name: Start Xvfb (Virtual Display)
        run: |
          Xvfb :99 -screen 0 1280x720x16 &
          export DISPLAY=:99

      - name: Run E2E Tests (Headed)
        env:
          CI: true
          DISPLAY: :99
          GOOGLE_EMAIL: ${{ secrets.GOOGLE_EMAIL }}
          GOOGLE_PASSWORD: ${{ secrets.GOOGLE_PASSWORD }}
        run: cd e2e && npx playwright test --headed --reporter=dot

      - name: Upload Playwright Artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-artifacts
          path: playwright-report
